
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /source


RUN git clone https://github.com/Mostafahiisham/voting-app.git
WORKDIR /source/voting-app/worker


RUN dotnet restore


RUN dotnet publish -c Release -o /app --self-contained false --no-restore


FROM mcr.microsoft.com/dotnet/runtime:7.0
WORKDIR /app


COPY --from=build /app .


ENTRYPOINT ["dotnet", "Worker.dll"]

