# Build stage
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /source

# Clone your repo
RUN git clone https://github.com/Mostafahiisham/voting-app.git
WORKDIR /source/voting-app/worker

# Restore dependencies
RUN dotnet restore

# Publish the app
RUN dotnet publish -c Release -o /app --self-contained false --no-restore

# Runtime stage
FROM mcr.microsoft.com/dotnet/runtime:7.0
WORKDIR /app

# Copy published output from build stage
COPY --from=build /app .

# Entry point
ENTRYPOINT ["dotnet", "Worker.dll"]

