FROM python:3.11-slim AS base

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    	curl \
   	git && \
    pip install flask gunicorn redis && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local/app
 
RUN git clone https://github.com/Mostafahiisham/voting-app/tree/375d12ef8d70d2038e3631c30919623456939681/voting 

WORKDIR /usr/local/app/voting-app


EXPOSE 80


CMD ["gunicorn", "app:app", "-b", "0.0.0.0:80", "--log-file", "-", "--access-logfile", "-", "--workers", "4", "--keep-alive", "0"]

    
