FROM node:18-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl tini git ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local/app

# Clone repo
RUN git clone https://github.com/Mostafahiisham/voting-app.git

WORKDIR /usr/local/app/voting-app/result 

# Install dependencies
RUN npm ci

ENV PORT=80
EXPOSE 80

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["node", "server.js"]

